dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
addons:
    chrome: stable
before_install:
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid
    --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0
    1920x1080x16"
    - sleep 3
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest
